try 
{
} 
catch( e ) 
{
	console.log( "exception: " + e );
	throw( e );
}